apiVersion: v1
appVersion: 5.0.0-rc.11
description: Voyager by AppsCode - Secure Ingress Controller for Kubernetes
icon: https://cdn.appscode.com/images/icon/voyager.png
maintainers:
- email: support@appscode.com
  name: appscode
name: voyager
sources:
- https://github.com/appscode/voyager
version: 2.2.0
