apiVersion: v1
description: 'Voyager by AppsCode - Secure HAProxy Ingress Controller for Kubernetes'
icon: https://cdn.appscode.com/images/icon/voyager.png
name: voyager
version: 9.0.0
appVersion: 9.0.0
sources:
  - https://github.com/appscode/voyager
maintainers:
  - name: appscode
    email: support@appscode.com
